export const productData = [
  {
    title:
      "Summer Men's Casual Sports Suit City Printed Sports Outdoor Jogging Sweatshirt Sweatpants Breathable Quick Drying 2 Piece Suit",
    productCode: "3729122",
    imageSrc: "/product-1/main-image-1.webp",
    discountPrice: "14.13",
    normalPrice: "30.72",
    discountRate: 1 - 14.13 / 30.72,
    rating: "4.0",
    ordersSold: "1356",
    minTime: 2,
    maxTime: 3,
    features: {
      color: [
        { option: "Black", colorImg: "/product-1/sub-image-1.webp" },
        { option: "White", colorImg: "/product-1/sub-image-2.webp" },
      ],
      size: [
        { option: "XL(65-69KG)" },
        { option: "XXL(70-74KG)" },
        { option: "XXXL(75-80KG)" },
      ],
    },
    subImageSrc: [
      "/product-1/main-image-1.webp",
      "/product-1/main-image-2.webp",
      "/product-1/main-image-3.webp",
      "/product-1/main-image-4.webp",
      "/product-1/main-image-5.webp",
      "/product-1/main-image-6.webp",
    ],
  },
  {
    title:
      "Nylon Sexy Women's Sports Bra Top Women Tight Elastic Gym Sport Yoga Bras Crop Top Yoga Clothes Stretch Women Sports Underwear",
    productCode: "1005006",
    imageSrc: "/product-2/main-image-3.webp",
    discountPrice: "7.93",
    normalPrice: "26.13",
    discountRate: 1 - 7.93 / 26.13,
    rating: "4.8",
    ordersSold: "2782",
    minTime: 3,
    maxTime: 5,
    features: {
      color: [
        { option: "Black", colorImg: "/product-2/sub-image-1.webp" },
        { option: "White", colorImg: "/product-2/sub-image-2.webp" },
        { option: "Velvet Pink", colorImg: "/product-2/sub-image-3.webp" },
        { option: "Blue", colorImg: "/product-2/sub-image-4.webp" },
        { option: "Violet", colorImg: "/product-2/sub-image-5.webp" },
      ],
      size: [
        { option: "S" },
        { option: "M" },
        { option: "L" },
        { option: "XL" },
      ],
    },
    subImageSrc: [
      "/product-2/main-image-1.webp",
      "/product-2/main-image-2.webp",
      "/product-2/main-image-3.webp",
      "/product-2/main-image-4.webp",
      "/product-2/main-image-5.webp",
      "/product-2/main-image-6.webp",
    ],
  },
  {
    title:
      "Quick dry Loose Joggers Sweatpants Men Casual Pants Gym Workout Sportswear Trousers Autumn Male Fitness Training Trackpants",
    productCode: "7126350",
    imageSrc: "/product-3/main-image-3.webp",
    discountPrice: "10.11",
    normalPrice: "24.42",
    discountRate: 1 - 10.11 / 24.42,
    rating: "4.2",
    ordersSold: "3473",
    minTime: 2,
    maxTime: 6,
    features: {
      color: [
        { option: "Black", colorImg: "/product-3/sub-image-1.webp" },
        { option: "White", colorImg: "/product-3/sub-image-2.webp" },
        { option: "Purple", colorImg: "/product-3/sub-image-3.webp" },
        { option: "Yellow", colorImg: "/product-3/sub-image-4.webp" },
      ],
      size: [
        { option: "M" },
        { option: "L" },
        { option: "XL" },
        { option: "XXL" },
        { option: "XXXL" },
      ],
    },
    subImageSrc: [
      "/product-3/main-image-1.webp",
      "/product-3/main-image-2.webp",
      "/product-3/main-image-3.webp",
      "/product-3/main-image-4.webp",
      "/product-3/main-image-5.webp",
      "/product-3/main-image-6.webp",
    ],
  },
  {
    title:
      "Velvet Smoking Jacket for Men Double Breasted Male Suit Blazer Slim Fit for Prom Party 1 Piece Groom Fashion Coat",
    productCode: "0204819",
    imageSrc: "/product-4/main-image-1.webp",
    discountPrice: "36.93",
    normalPrice: "95.25",
    discountRate: 1 - 36.93 / 95.25,
    rating: "4.0",
    ordersSold: "952",
    minTime: 4,
    maxTime: 8,
    features: {
      color: [{ option: "Burgundy", colorImg: "/product-4/sub-image-1.webp" }],
      size: [
        { option: "XS (US34)" },
        { option: "S (US36)" },
        { option: "M (US38)" },
        { option: "L (US40)" },
        { option: "XL (US42)" },
        { option: "XXL (US44)" },
        { option: "XXXL (US46)" },
        { option: "4XL (US48)" },
        { option: "5XL (US50)" },
      ],
    },
    subImageSrc: [
      "/product-4/main-image-1.webp",
      "/product-4/main-image-2.webp",
      "/product-4/main-image-3.webp",
    ],
  },
  {
    title:
      "Summer Korean Fashion Men's Polo Shirt Luxury Embroidered Cotton Lapel Collar Short Sleeves Tops",
    productCode: "8527090",
    imageSrc: "/product-5/main-image-1.webp",
    discountPrice: "12.04",
    normalPrice: "16.76",
    discountRate: 1 - 12.04 / 16.76,
    rating: "3.6",
    ordersSold: "2246",
    minTime: 2,
    maxTime: 4,
    features: {
      color: [
        { option: "Navy", colorImg: "/product-5/sub-image-1.webp" },
        { option: "Lake Blue", colorImg: "/product-5/sub-image-2.webp" },
        { option: "Gray", colorImg: "/product-5/sub-image-3.webp" },
        { option: "Pink", colorImg: "/product-5/sub-image-4.webp" },
        { option: "White", colorImg: "/product-5/sub-image-5.webp" },
        { option: "Yellow", colorImg: "/product-5/sub-image-6.webp" },
      ],
      size: [
        { option: "S(48-55kg)" },
        { option: "M(55-60kg)" },
        { option: "L(60-75kg)" },
        { option: "XL(75-80kg)" },
        { option: "2XL(80-85kg)" },
        { option: "3XL(85-90kg)" },
        { option: "4XL(90-95kg)" },
      ],
    },
    subImageSrc: [
      "/product-5/main-image-1.webp",
      "/product-5/main-image-2.webp",
      "/product-5/main-image-3.webp",
      "/product-5/main-image-4.webp",
      "/product-5/main-image-5.webp",
      "/product-5/main-image-6.webp",
    ],
  },
  {
    title:
      "Plus Size Vest Tops for Women Clothing Summer Sexy Large Size Slim Pullover Short Sleeve Female Korean Oversized Tank T-Shirt",
    productCode: "6760822",
    imageSrc: "/product-6/main-image-1.webp",
    discountPrice: "4.75",
    normalPrice: "21.79",
    discountRate: 1 - 4.75 / 21.79,
    rating: "4.1",
    ordersSold: "1306",
    minTime: 3,
    maxTime: 4,
    features: {
      color: [
        { option: "Black", colorImg: "/product-6/sub-image-1.webp" },
        { option: "Green", colorImg: "/product-6/sub-image-2.webp" },
        { option: "Red", colorImg: "/product-6/sub-image-3.webp" },
        { option: "Navy Blue", colorImg: "/product-6/sub-image-4.webp" },
      ],
      size: [
        { option: "XL" },
        { option: "XXL" },
        { option: "XXXL" },
        { option: "4XL" },
      ],
    },
    subImageSrc: [
      "/product-6/main-image-1.webp",
      "/product-6/main-image-2.webp",
      "/product-6/main-image-3.webp",
      "/product-6/main-image-4.webp",
      "/product-6/main-image-5.webp",
      "/product-6/main-image-6.webp",
    ],
  },
  {
    title:
      "Fashion Women Loose Style Overalls Boho Solid Color Playsuit Sleeveless Rompers Summer Casual Clothes Jumpsuit with Pockets",
    productCode: "8009288",
    imageSrc: "/product-7/main-image-1.webp",
    discountPrice: "4.53",
    normalPrice: "19.20",
    discountRate: 1 - 4.53 / 19.20,
    rating: "4.0",
    ordersSold: "3544",
    minTime: 3,
    maxTime: 7,
    features: {
      color: [
        { option: "Light Green", colorImg: "/product-7/sub-image-1.webp" },
        { option: "Black", colorImg: "/product-7/sub-image-2.webp" },
        { option: "Peach", colorImg: "/product-7/sub-image-3.webp" },
        { option: "Red", colorImg: "/product-7/sub-image-4.webp" },
        { option: "Emerald Green", colorImg: "/product-7/sub-image-5.webp" },
        { option: "Pink", colorImg: "/product-7/sub-image-6.webp" },
      ],
      size: [
        { option: "S" },
        { option: "M" },
        { option: "L" },
        { option: "XL" },
        { option: "XXL" },
        { option: "XXXL" },
      ],
    },
    subImageSrc: [
      "/product-7/main-image-1.webp",
      "/product-7/main-image-2.webp",
      "/product-7/main-image-3.webp",
      "/product-7/main-image-4.webp",
      "/product-7/main-image-5.webp",
      "/product-7/main-image-6.webp",
    ],
  },
  {
    title:
      "Baseball Jacket Men Fashion Baseball Jersey Casual Long Sleeve Jacket Coats Fashion Loose Male Coat Hooded Baseball Jersey New",
    productCode: "0629717",
    imageSrc: "/product-8/main-image-1.webp",
    discountPrice: "25.68",
    normalPrice: "46.42",
    discountRate: 1 - 25.68 / 46.42,
    rating: "4.2",
    ordersSold: "1773",
    minTime: 4,
    maxTime: 5,
    features: {
      color: [
        { option: "Black", colorImg: "/product-8/sub-image-1.webp" },
        { option: "Green", colorImg: "/product-8/sub-image-2.webp" },
        { option: "Blue", colorImg: "/product-8/sub-image-3.webp" },
      ],
      size: [
        { option: "M" },
        { option: "L" },
        { option: "XL" },
        { option: "XXL" },
        { option: "3XL" },
      ],
    },
    subImageSrc: [
      "/product-8/main-image-1.webp",
      "/product-8/main-image-2.webp",
      "/product-8/main-image-3.webp",
      "/product-8/main-image-4.webp",
      "/product-8/main-image-5.webp",
      "/product-8/main-image-6.webp",
    ],
  },
  {
    title:
      "Solid Pleated Two Piece Set For Women Summer Women's Two Piece Casual Long Sleeve Short Sets Fashion Button Outfits Suit",
    productCode: "5006779",
    imageSrc: "/product-9/main-image-1.webp",
    discountPrice: "11.87",
    normalPrice: "13.37",
    discountRate: 1 - 11.87 / 13.37,
    rating: "3.8",
    ordersSold: "1052",
    minTime: 5,
    maxTime: 10,
    features: {
      color: [
        { option: "Rose", colorImg: "/product-9/sub-image-1.webp" },
        { option: "Green", colorImg: "/product-9/sub-image-2.webp" },
        { option: "Orange", colorImg: "/product-9/sub-image-3.webp" },
      ],
      size: [
        { option: "S" },
        { option: "M" },
        { option: "L" },
        { option: "XL" },
        { option: "XXL" },
      ],
    },
    subImageSrc: [
      "/product-9/main-image-1.webp",
      "/product-9/main-image-2.webp",
      "/product-9/main-image-3.webp",
      "/product-9/main-image-4.webp",
      "/product-9/main-image-5.webp",
      "/product-9/main-image-6.webp",
    ],
  },
  {
    title:
      "Men Vest Autumn Jackets Thick Vests Man Sleeveless Coats Male Warm Cotton-Padded Waistcoat Men Gilet Veste Hommes",
    productCode: "7812654",
    imageSrc: "/product-10/main-image-1.webp",
    discountPrice: "8.93",
    normalPrice: "10.43",
    discountRate: 1 - 8.93 / 10.43,
    rating: "4.8",
    ordersSold: "4105",
    minTime: 3,
    maxTime: 6,
    features: {
      color: [
        { option: "Black", colorImg: "/product-10/sub-image-1.webp" },
        { option: "Blue", colorImg: "/product-10/sub-image-2.webp" },
        { option: "Red", colorImg: "/product-10/sub-image-3.webp" },
      ],
      size: [
        { option: "M" },
        { option: "L" },
        { option: "XL" },
        { option: "XXL" },
        { option: "XXXL" },
        { option: "4XL" },
      ],
    },
    subImageSrc: [
      "/product-10/main-image-1.webp",
      "/product-10/main-image-2.webp",
      "/product-10/main-image-3.webp",
      "/product-10/main-image-4.webp",
      "/product-10/main-image-5.webp",
      "/product-10/main-image-6.webp",
    ],
  },
  {
    title:
      "Trendy Spring Sweater Loose Thermal Thick Streetwear Men Winter Sweater",
    productCode: "4916755",
    imageSrc: "/product-11/main-image-2.webp",
    discountPrice: "11.45",
    normalPrice: "17.58",
    discountRate: 1 - 11.45 / 17.58,
    rating: "4.0",
    ordersSold: "1962",
    minTime: 2,
    maxTime: 5,
    features: {
      color: [
        { option: "Black", colorImg: "/product-11/sub-image-1.webp" },
        { option: "Apricot", colorImg: "/product-11/sub-image-2.webp" },
        { option: "Green", colorImg: "/product-11/sub-image-3.webp" },
        { option: "Blueberry", colorImg: "/product-11/sub-image-4.webp" },
        { option: "Grey", colorImg: "/product-11/sub-image-5.webp" },
      ],
      size: [
        { option: "M" },
        { option: "L" },
        { option: "XL" },
        { option: "2XL" },
        { option: "3XL" },
      ],
    },
    subImageSrc: [
      "/product-11/main-image-1.webp",
      "/product-11/main-image-2.webp",
      "/product-11/main-image-3.webp",
      "/product-11/main-image-4.webp",
      "/product-11/main-image-5.webp",
      "/product-11/main-image-6.webp",
    ],
  },
  {
    title:
      "3 Piece Set Tracksuit Women Fashion Temperament Designer Long Sleeve Stand Collar Casual Sport Outfits Tracksuit Suit Set",
    productCode: "6372428",
    imageSrc: "/product-12/main-image-3.webp",
    discountPrice: "22.58",
    normalPrice: "54.10",
    discountRate: 1 - 22.58 / 54.10,
    rating: "4.3",
    ordersSold: "2417",
    minTime: 3,
    maxTime: 8,
    features: {
      color: [
        { option: "Grey", colorImg: "/product-12/sub-image-1.webp" },
        { option: "Black", colorImg: "/product-12/sub-image-2.webp" },
        { option: "Blue", colorImg: "/product-12/sub-image-3.webp" },
        { option: "Brown", colorImg: "/product-12/sub-image-4.webp" },
        { option: "Khaki", colorImg: "/product-12/sub-image-5.webp" },
        { option: "Orange", colorImg: "/product-12/sub-image-6.webp" },
      ],
      size: [
        { option: "S" },
        { option: "M" },
        { option: "L" },
        { option: "XL" },
        { option: "XXL" },
      ],
    },
    subImageSrc: [
      "/product-12/main-image-1.webp",
      "/product-12/main-image-2.webp",
      "/product-12/main-image-3.webp",
      "/product-12/main-image-4.webp",
      "/product-12/main-image-5.webp",
      "/product-12/main-image-6.webp",
    ],
  },
];
